### ISSUE TITLE
VirtualStygmergy: Difference Between gets/get and puts/put

### ISSUE THREAD

**Issue by cmuell89** [xuefengchang/micros_swarm_framework#10]
What is the difference between gets and get?

What is the difference between puts and put?

Thanks!

**Comment by xuefengchang** [comment]
puts and gets simplified the consistency protocol of VirtualStygmergy to reduce the occupied network bandwidth, they can only guarantee the consistency when the upper application reading(gets) and writing(puts) periodically  in theory.  Thanks! 
@cmuell89
