### ISSUE TITLE
ROS2 Compability

### ISSUE THREAD

**Issue by derektan95** [xuefengchang/micros_swarm_framework#11]
Hi, 

Just wanted to check, does this work with ROS2 (Eloquent / Foxy)? Thanks alot!

**Comment by xuefengchang** [comment]
> Hi,
> 
> Just wanted to check, does this work with ROS2 (Eloquent / Foxy)? Thanks alot!

Currently not supported yet.

**Comment by derektan95** [comment]
Ok, thanks!
