### ISSUE TITLE
Missing GSDF msgs

### ISSUE THREAD

**Issue by eraserpencil** [xuefengchang/micros_swarm_framework#4]
Encountered an error whilst trying to compile

In file included from /home/ryan/mov/catkin_ws/src/micros_swarm_framework/core/micros_swarm/include/micros_swarm/comm_interface.h:29:0,
                 from /home/ryan/mov/catkin_ws/src/micros_swarm_framework/core/udp_bc_broker/include/udp_bc_broker/udp_bc_broker.h:30,
                 from /home/ryan/mov/catkin_ws/src/micros_swarm_framework/core/udp_bc_broker/src/udp_bc_broker.cpp:26:
/home/ryan/mov/catkin_ws/src/micros_swarm_framework/core/micros_swarm/include/micros_swarm/packet_parser.h:38:34: fatal error: gsdf_msgs/CommHeader.h: No such file or directory
compilation terminated.

**Comment by xuefengchang** [comment]
I think that there may be bugs in some CmakeList.txt files. 
I will repairs them in the next version.
I recommend you to download the latest source code from the github pages and compile manually, using the command:` catkin_make  -j1`
that may be valid.
