### ISSUE TITLE
running over multiple machines

### ISSUE THREAD

**Issue by joshferns** [xuefengchang/micros_swarm_framework#5]
Hi, 
Would  like to know how  should I go about running the demos over multiple computers?

Are there any more tutorials for using the framework?

The aim is to run one swarm agent on one raspberry pi and not all of them as 'objects' of the same code.
(still getting started with ROS so apologies if this is a noob question)

Thank you in advance.

**Comment by xuefengchang** [comment]
@joshferns 
First, configure the multi machine ROS, reference: [http://wiki.ros.org/ROS/Tutorials/MultipleMachines](url)
Then, you need to modify the daemon_node.launch and the app(1,2,3).launch file and specify the robot id value. Each robot corresponds to a unique robot id value. 
Taking an example of robot_0:
------------
daemon_node.launch
```
<launch>
    <!--set runtime core parameters-->
    <param name="publish_robot_id_duration" type="double" value="0.1"/>
    <param name="publish_swarm_list_duration" type="double" value="5.0"/>
    <param name="default_neighbor_distance" type="double" value="40"/>
    <param name="total_robot_numbers" type="int" value="20"/>
    
    <!--comm type-->
    <param name="comm_type" type="string" value="ros_broker/ROSBroker"/>
    <!--use UDP BroadCast for multi agents/-->
    <!--param name="comm_type" type="string" value="udp_bc_broker/UDPBCBroker"/-->

    <group ns="robot_0">
        <node pkg="micros_swarm" type="daemon_node" name="daemon_node0" output="screen">
            <param name="robot_id" type="int" value="0"/>
        </node>
    </group>
</launch>
```
-------------
app1.launch
```
<launch>
    <group ns="robot_0">  
        <node pkg="app_loader" type="app_loader_node" name="app_loader_node0" output="screen">  
            <param name="app_name" type="string" value="app1"/>  
            <param name="app_type" type="string" value="app1/App1"/>  
        </node>  
    </group>  
</launch>  
```

**Comment by joshferns** [comment]
Thank you.
