### ISSUE TITLE
Swarm Simulation in Gazebo

### ISSUE THREAD

**Issue by anubhav1997** [xuefengchang/micros_swarm_framework#6]
What are the steps to run the simulation in gazebo? 
I ran the following commands:
1. roslaunch micros_swarm_gazebo swarm_in_gazebo.launch
2. roslaunch micros_swarm_gazebo daemon_node.launch
3. roslaunch micros_swarm_gazebo gazebo_flocking.launch 
However the UAVs in gazebo aren't moving. If I do rostopic echo for any of the topic the values are changing, however it is not visible in simulation. 

Thanks in advance

**Comment by chesternimiz** [comment]
Sorry for the inconvenience. A new version has been pushed to fix this problem.
1. There's a mismatch of <group ns='robot_X'> and <group ns='uavX'> of these launch files. Now the namespaces are all set to <group ns='uavX'>.
2. The latest version of hector_quadrotor disables the motors of the UAVs as default. To take off, service /uavX/enable_motors should be called first.  The new app code calls this service at start.

**Comment by anubhav1997** [comment]
Thank you
